#pragma once

namespace Cjing3D {
namespace Gui {

	enum class UI_EVENT_TYPE
	{
		UI_EVENT_UNKNOW,

		UI_EVENT_MOUSE_ENTER,
		UI_EVENT_MOUSE_LEAVE,
		UI_EVENT_MOUSE_MOTION,

		UI_EVENT_MOUSE_BUTTON_DOWN,
		UI_EVENT_MOUSE_BUTTON_UP,
		UI_EVENT_MOUSE_BUTTON_CLICK,

		UI_EVENT_KEYBOARD_KEYDOWN,
		UI_EVENT_KEYBOARD_KEYUP,
	};

}
}