#ifndef _CONSTANT_BUFFER_DEFINE_H_
#define _CONSTANT_BUFFER_DEFINE_H_


// CBUFFER SLOT (register b##slot)
#define CBSLOT_RENDERER_FRAME   0
#define CBSLOT_RENDERER_CAMERA  1
#define CBSLOT_RENDERER_MATERIAL 2
#define CBSLOT_IMAGE 3
#define CBSLOT_POSTPROCESS 4
#define CBSLOT_MIPMAPGENERATE 5
#define CBSLOT_TERRAIN 6


#endif