#ifndef _SHADERINTEROP_DEFINE_H_
#define _SHADERINTEROP_DEFINE_H_

// CBUFFER SLOT (register b##slot)
#define CBSLOT_RENDERER_FRAME   0
#define CBSLOT_RENDERER_CAMERA  1
#define CBSLOT_RENDERER_MATERIAL 2
#define CBSLOT_IMAGE 3
#define CBSLOT_POSTPROCESS 4
#define CBSLOT_MIPMAPGENERATE 5

// TEXTURE SLOT (register t##slot)
#define TEXTURE_SLOT_SHADOW_ARRAY_2D 0

#define TEXTURE_SLOT_0 1
#define TEXTURE_SLOT_1 2
#define TEXTURE_SLOT_2 3
#define TEXTURE_SLOT_3 4

#define TEXTURE_SLOT_UNIQUE_0 5
#define TEXTURE_SLOT_UNIQUE_1 6

#define TEXTURE_BASECOLOR_MAP	TEXTURE_SLOT_0
#define TEXTURE_NORMAL_MAP		TEXTURE_SLOT_1
#define TEXTURE_SURFACE_MAP		TEXTURE_SLOT_2

// STRUCTUREDBUFFRE SLOT
#define SBSLOT_SHADER_LIGHT_ARRAY 7
#define SBSLOT_MATRIX_ARRAY 8

#define SHADER_MATRIX_COUNT 128
#define SHADER_LIGHT_COUNT 128

// SAMPLER SLOT (register s##slot)
#define SAMPLER_SLOT_0 0
#define SAMPLER_SLOT_1 1
#define SAMPLER_COMPARISON_SLOT 2

#define SAMPLER_LINEAR_CLAMP_SLOT SAMPLER_SLOT_0
#define SAMPLER_ANISOTROPIC_SLOT  SAMPLER_SLOT_1

#endif