#ifndef _SHADERINTEROP_DEFINE_H_
#define _SHADERINTEROP_DEFINE_H_

// CBUFFER SLOT (register b##slot)
#define CBSLOT_RENDERER_FRAME   0
#define CBSLOT_RENDERER_CAMERA  1
#define CBSLOT_RENDERER_MATERIAL 2
#define CBSLOT_IMAGE 3
#define CBSLOT_POSTPROCESS 4

// TEXTURE SLOT (register t##slot)
#define TEXTURE_SLOT_0 0
#define TEXTURE_SLOT_1 1
#define TEXTURE_SLOT_2 2
#define TEXTURE_SLOT_3 3

// STRUCTUREDBUFFRE SLOT
#define SHADER_LIGHT_ARRAY_SLOT 4
#define SHADER_LIGHT_COUNT 128

#define TEXTURE_BASECOLOR_MAP	TEXTURE_SLOT_0
#define TEXTURE_NORMAL_MAP		TEXTURE_SLOT_1
#define TEXTURE_SURFACE_MAP		TEXTURE_SLOT_2

// SAMPLER SLOT (register s##slot)
#define SAMPLER_LINEAR_CLAMP_SLOT 0
#define SAMPLER_ANISOTROPIC_SLOT 1

#endif